In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
#from adspy_shared_utilities import (
#plot_class_regions_for_classifier_subplot)

In [8]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

#Doing some data wrangling, erasing columns not relevant and categorizing string features into floats
df_train = df_train.drop(['Name','Ticket','Cabin'],axis=1).replace({'Sex': {'male': 1, 'female': 0}}).replace({'Embarked': {'S': 0, 'C': 1, 'Q': 2}})
df_train = df_train.dropna()
df_test = df_test.drop(['Name','Ticket','Cabin'],axis=1).replace({'Sex': {'male': 1, 'female': 0}}).replace({'Embarked': {'S': 0, 'C': 1, 'Q': 2}}).dropna()

#Defining X_train and y_train
X_train = df_train.drop('Survived',axis=1)
y_train = df_train['Survived']

clf = LogisticRegression(C=100).fit(X_train, y_train)
print('the score of this logistic regression model is: ', clf.score(X_train, y_train))

the score of this logistic regression model is:  0.7963483146067416

C:\Users\pecha\AppData\Local\Temp\ipykernel_22984\4269825155.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train = df_train.drop(['Name','Ticket','Cabin'],axis=1).replace({'Sex': {'male': 1, 'female': 0}}).replace({'Embarked': {'S': 0, 'C': 1, 'Q': 2}})
C:\Users\pecha\AppData\Local\Temp\ipykernel_22984\4269825155.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_test = df_test.drop(['Name','Ticket','Cabin'],axis=1).replace({'Sex': {'male': 1, 'female': 0}}).replace({'Embarked': {'S': 0, 'C': 1, 'Q': 2}}).dropna()
c:\Users\pecha\anaconda3\envs\mydsenv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [14]:
prediction = df_test.copy()

prediction['Survived'] = clf.predict(df_test)

prediction1 = prediction[['PassengerId','Survived']]
prediction

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Survived
0,892,3,1,34.5,0,0,7.8292,2,0
1,893,3,0,47.0,1,0,7.0000,0,0
2,894,2,1,62.0,0,0,9.6875,2,0
3,895,3,1,27.0,0,0,8.6625,0,0
4,896,3,0,22.0,1,1,12.2875,0,1
...,...,...,...,...,...,...,...,...,...
409,1301,3,0,3.0,1,1,13.7750,0,1
411,1303,1,0,37.0,1,0,90.0000,2,1
412,1304,3,0,28.0,0,0,7.7750,0,1
414,1306,1,0,39.0,0,0,108.9000,1,1
415,1307,3,1,38.5,0,0,7.2500,0,0

In [13]:
prediction1.to_csv('Submission.csv',index=False)